name: CD - Deploy Users API with Docker

on:
  push:
    branches: [ "production" ]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image with 2 tags
      run: |
        docker build -t klztt/fcg-users-api:latest \
                     -t klztt/fcg-users-api:${{ github.sha }} .

    - name: Push Docker image (latest + sha)
      run: |
        docker push klztt/fcg-users-api:latest
        docker push klztt/fcg-users-api:${{ github.sha }}
